### ISSUE TITLE
Handle "no license" default set in a migrated collection

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1374] opened 2021-04-27 13:39 UTC
This error was caused during user testing of migrated content. 

The user had previously attempted to access a list of deposits for a migrated collection and was unable to. This is a known issue that appears to be caused by the collection setting of "no license" not being migrated collectively and the collection not having a license option selected (#1252). I asked him to set a license for the collection, which he did, and which fixed his inability to access the deposits list, but then his attempt to deposit a new item in this collection failed. Below is the honeybadger report that this attempt generated. The items shows 'deposit in progress" but does not finish.

Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/77802772

TypeError: Parameter 'license_id': Expected type String, got type NilClass Caller: /opt/app/h2/happy-heron/releases/20210423110856/app/components/works/license_component.rb:28 Definition: /opt/app/h2/happy-heron/releases/20210423110856/app/models/license.rb:73

Summary

works#new

URL: https://sul-h2-stage.stanford.edu/collections/650/works/new?work_type=music&subtype%5B%5D=Musical+transcription

Hostname: sul-h2-stage.stanford.edu

Context

user_scope: user
user_id: 357
Trace

app/components/works/license_component.rb:28:in `license_from_collection`
app/components/works/license_component.html.erb:19:in `call`
app/components/works/form_component.html.erb:33:in `block in call`

**Comment by jcoyne** [comment] 2021-05-05 18:07
This a problem with the migration script where the license is either blank or nil.  However h2 expects it to be the value "no license".

**Comment by jcoyne** [comment] 2021-05-05 18:23
Duplicate of #1374

**Closed by jcoyne** 2021-05-05 18:23 UTC
Labels: PO, R1.0, bug, user testing
