### ISSUE TITLE
Publication and Creation dates must require a month if a day is selected

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#524] opened 2020-11-19 21:57 UTC
Valid date options for publication date and creation date are:
year only
year and month only 
year, month, and day

Not allowed:
day only
month only
day and month only 
year and day

![Screen Shot 2020-11-19 at 1.57.41 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/96673ab4-c3e9-479c-bd74-6b83701e63b7)

**Comment by jcoyne** [comment] 2020-11-21 00:54
Is this a duplicate of #373?

**Comment by amyehodge** [comment] 2020-11-23 18:16
@jcoyne Looks like partially. This one includes the Creation dates as well. This one is more detailed. Perhaps we should keep this one and close #373?

**Comment by amyehodge** [comment] 2020-11-23 18:17
Ah, yes, it is. Sorry, @jcoyne I swear I searched for these things before I made tickets and I just didn't find this one.

**Closed** 2020-11-24 00:56 UTC
Labels: PO
