### ISSUE TITLE
Should creating a collection create a new APO?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#184] opened 2020-10-20 15:49 UTC

**Comment by mjgiarlo** [comment] 2020-10-26 18:18
We are not sure yet. We don't *think* this is driving any unique functional requirements in the application. We also think this is an implementation detail. Leaving open for now.

**Comment by andrewjbtw** [comment] 2020-12-12 00:09
**Short answer** 
Probably not

**Longer answer**
We likely need to be able to use H2 to deposit under different APOs, but the current Hydrus behavior, which creates an APO specially for every single collection, is not likely to be needed.

**Even longer answer, with analysis**

I approached this question by asking the following:

1. What does an APO represent in terms of policy?
2. What does the SDR system do using APOs?
3. What would H2 need to do where an APO might be involved?
4. What do we need to do with the existing Hydrus items and their many APOs?

1. What is an APO? (emphasis on the "policy" in "Administrative Policy Object")

By policy, everything in SDR is governed by an Agreement. The APO is supposed to be the machine actionable translation of that agreement. (These agreements are also deposited in SDR.) Every APO is linked to its agreement via the RELS-EXT. Every collection and item deposited under that APO should be governed by that agreement.

For H2 the question then is: is anything deposited governed by an agreement other than the Hydrus deposit agreement that governs all the Hydrus APOs? Hydrus collections exist mostly for organizational reasons, not for separating agreements. Campus depositors agree to the same terms of service when depositing. So making a new APO for each collection doesn't appear to be necessary for this.

The exception might be SUL depositors who use self-deposit for items that eventually make their way into other SUL APOs. But that doesn't seem like enough of a reason to create a new APO for every single collection.

2. What do APOs do within the system? (emphasis on the machine actionable)

APOs can be used for a lot of things, including functions I may not even know about, but the main ones are:

- store a default set of access rights ("discover" and "read")
- store a default use and reproduction statement
- store a default license
- within Argo, enforce view and edit permissions
- within Argo, populate the menus that allow people to select a collection (for registration or to change collections)
- within Argo, populate the list of available workflows on the registration form
- store instructions on which workflows to run when processing objects (not frequently used, but I believe the ETD workflow uses this to route objects to SearchWorks release automatically, and web archive APOs have some workflow settings)

Of those functions, the last four do not appear relevant to H2, or at least tangential to the question of whether a collection needs to create an APO.

That leaves three pieces of data in APOs that are directly H2-relevant: rights, use and reproduction statements, licenses 

Let's start with rights:

- an APO has a default set of rights that **can** be applied to any object in the APO (this is in the defaultObjectRights datastream)
- these default rights do not have to be applied automatically, and can always be overridden on the individual object level
- there are two big advantages to storing defaults
  - they can be applied when an object is created by inheriting the rights from the APO
  - there is a bulk job in Argo that allows us to apply the APO defaults to groups of items, which is helpful when objects are moved from a different APO or when the APO's own defaults have been modified and now objects have to be updated
- in Hydrus, I believe all objects get the APO defaults for their collection's APO, except for collections where depositors can choose from multiple options (world or Stanford)

If H2 sets the object rights when objects are created, it does not necessarily matter what the APO defaults are. They'll get the rights that are set from the H2 form. Care would have to be taken not to use the APO defaults to override what H2 has set. It is likely that some number of objects will differ from APO defaults because objects can change rights over time (start as Stanford, later change to World). It would be great to not have to change the APO in that situation.

Next, use and reproduction statements:

- Most of the same considerations that apply to rights apply here
- The main question is if any collection would use a statement different than the default statement (already in the [Hydrus Ur-APO](https://argo.stanford.edu/view/druid:zw306xn5593))
- I'm not sure if you can set a special statement in the H2 collection form - do people have an option to change it? H2 could potentially send this information too if the SDR API supports it, instead of relying on an APO to carry it

Finally, licenses:

- Similar to rights: there are APO defaults, but there are likely to be license choices that differ from the APO defaults
- Since the H2 form lets you set licenses, the APO may not matter here

Bottom line is that I don't think a collection needs to have its own APO in order to set rights, statements, and licenses, as long as we can set them to values that vary from the APO defaults.

3. What does H2 need to do with APOs? (the tl;dr)

Summarizing the above

- H2 needs to deposit collections and objects under an APO that is under an agreement that governs those collections and objects
- Most H2 deposits will be governed by the same self-deposit agreement
- Collections don't need their own APOs as long as the rights, statements, and licenses can be created properly for those collections and the objects within them
- There are use cases, mainly internal SUL ones, for depositing under an APO other than the self-deposit APO
 - This could be addressed by making it possible for H2 to deposit into a pre-configured APO for certain collections
- It should not be necessary to make a collection automatically create its own APO

4. Migration considerations

Virtually all self-deposit items are under a special Hydrus APO, which is nested under the Hydrus Ur-APO, which links to [the Hydrus agreement](https://argo.stanford.edu/view/druid:mc322hh4254). If H2 is going to use a single APO, or a smaller set of APOs that differ only in certain defaults, we would need to move existing items and collections to the appropriate APO or APOs. This is already supported in Argo and should not require special tooling. 

For bringing these objects into H2, we would need to make sure H2 is set to go to the right APO, so there is some work to do to coordinate the changes. Once we change an object's APO, Hydrus might not work anymore for that object, so it could be a hard cut-over.

Open question for migration: do we have any Hydrus APOs that deviate from the Ur-APO defaults in terms of statements or licenses? If so, we'll need to work out what to do with the collections and objects that use non-standard values. I'd hoped to export all the Hydrus APO statements and examine them this week but won't be able to until January.

**Comment by amyehodge** [comment] 2021-01-04 21:38
Thanks for this detailed analysis, @andrewjbtw 

> The main question is if any collection would use a statement different than the default statement (already in the Hydrus Ur-APO)
I'm not sure if you can set a special statement in the H2 collection form - do people have an option to change it? H2 could potentially send this information too if the SDR API supports it, instead of relying on an APO to carry it

Hydrus does not allow you to include a special statement, and H2 currently does not allow this either. However, 1) this doesn't mean that this hasn't been done manually later (I suspect it has, actually, so I'm glad you plan to look for these), and 2) we have user requests for this, so we do hope to be able to add special/custom use statements (and licenses) in the future.

**Comment by jcoyne** [comment] 2021-06-25 17:25
@amyehodge @andrewjbtw can we close this ticket?

**Comment by amyehodge** [comment] 2021-06-25 17:27
I'm leaving that to @andrewjbtw

**Comment by andrewjbtw** [comment] 2021-06-25 17:59
We answered this question with "no".

**Closed by andrewjbtw** 2021-06-25 17:59 UTC
Labels: question
