### ISSUE TITLE
Files deposited under Stanford only access rights are available for world download on PURL

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/happy-heron#1987] opened 2021-08-19 21:55 UTC
A user has uncovered a bug in the access rights. 

Files deposited with the setting of Stanford-only access are downloadable by non-authenticated users.

The access rights setting in Argo says "stanford and world (file)" which I don't believe I have ever seen before.

Here is a test item that I created to reproduce the error reported by the user:
druid:sj995gy8148
https://sdr.stanford.edu/works/4664

**Comment by jcoyne** [comment] 2021-08-19 22:03
I believe this is a duplicate of https://github.com/sul-dlss/happy-heron/issues/1933

**Comment by amyehodge** [comment] 2021-08-19 22:07
Agreed

**Closed by amyehodge** 2021-08-19 22:07 UTC
