### ISSUE TITLE
Custom publisher statements should support formatting

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3127] opened 2023-06-26 21:32 UTC
The customer published statement should support hyperlinks, i.e. a fully written out hyperlink in this box should work as a hyperlink on the purl page.  It should also support line breaks.

Note: we believe this will require changes to PURL.

**Comment by amyehodge** [comment] 2023-10-31 14:44
I have confirmed that the hyperlinks are already working as desired.

**Comment by lwrubel** [comment] 2023-11-02 14:24
Thanks for confirming about the links. Closing since the linebreaks are added with #3404.

**Closed by lwrubel** 2023-11-02 14:24 UTC
Labels: 2023
