### ISSUE TITLE
Evaluate whether we are searching too much when looking up SUNet IDs

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2451] opened 2022-08-19 19:37 UTC
@peetucket and I were reviewing the SUNet ID searching for adding users to collections and got discussing some more subtle points of the search.

When I search StanfordWho (stanfordwho.stanford.edu) I don't find all the people that the search in H2 finds. 

In an H2 search of my name I find, in order:
amy: Searight, Amy Elizabeth - Former student 
amyh: Hurlbut, Amy Orsak - Former student
amyho: Ho, Man-Yee - Former student
amyhodge: Hodge, Amy E. - Science and Engineering Resource Group, Science Data Librarian

The last entry is the only one I can find at StanfordWho.

Because the other three are all former students, I'm wondering if we are searching every SUNet that ever was, when we only need to be searching the subset that are active SUNets. By searching a smaller set of IDs we would return fewer results and may have fewer issues with a lag between typing and the display of results. 

Also, while I was talking with Peter, I was once able to search for "amyhodge" but clicked the "Add" button quickly enough that the "amyho" result was still there and inadvertently added "Amy Orsak Hurlbut" instead of me. Perhaps getting fewer results could help with that as well?

@peetucket Anything else you'd like to add about this?

**Comment by peetucket** [comment] 2022-08-19 20:13
For developers, I would suggest a couple actions here:

- look at the code that makes the API calls out to the directory to find people: https://github.com/sul-dlss/happy-heron/blob/main/app/services/account_service.rb  and then see if there is any documentation for this API endpoint that allows us to further restrict to active users only
- see if there is a more intelligent way of making that API call...right now one call happens after each character you type (see https://github.com/sul-dlss/happy-heron/blob/main/app/javascript/controllers/collection_participant_form_controller.js#L63-L82 and https://github.com/sul-dlss/happy-heron/blob/main/app/components/collections/update/reviewers_component.html.erb#L24) and if you type quickly, I can see this potentially causing some issues (with the typing happening much faster than the API call and response can be completed)

**Comment by lwrubel** [comment] 2022-08-22 18:14
Maybe using debounce would be useful here to reduce how often the API call is made.

**Comment by jcoyne** [comment] 2022-09-01 14:16
@amyehodge Is this a duplicate of #2524

**Comment by amyehodge** [comment] 2022-09-01 14:53
@jcoyne, @peetucket suggested I make this ticket and I believe it's more about the general approach than the existing bug. @peetucket can you comment further? Thanks.

**Comment by peetucket** [comment] 2022-09-01 15:30
#2551 should prevent us from searching too many times too quickly -- hopefully this will make this interaction more stable and I think we can close this ticket.  However, if this doesn't fix the issues, we will probably just need to create a new ticket, referencing this one so we can see what was already done.

**Closed by peetucket** 2022-09-01 15:30 UTC
Labels: PO, 2022
