### ISSUE TITLE
Additional columns need to be added to the collection details table

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#689] opened 2020-12-04 23:10 UTC
A few things are missing from the collection details table. The wireframes show the following:
![Screen Shot 2020-12-04 at 3.00.06 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/23e4429f-b7b5-4a54-904c-546b19c5245e)

See Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.jlexdek3dzin

This table needs:
1. Depositor
2. # of files
3. Deposit size 
4. share icon to the right of the PURL (only if PURL present)

**Comment by jcoyne** [comment] 2020-12-05 15:54
@amyehodge this sounds like a duplicate of #674

**Comment by amyehodge** [comment] 2020-12-07 18:03
Agreed, @jcoyne . Closing.

**Closed** 2020-12-07 18:03 UTC
Labels: PO
