### ISSUE TITLE
Allow users to version objects released from embargo

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1352] opened 2021-04-21 21:34 UTC
I attempted to version https://sul-h2-stage.stanford.edu/works/13246 as discussed with @jcoyne and @mjgiarlo earlier today in sprint planning. This item was embargoed and then released the next day on schedule. Three versions are recorded in Argo but only two in H2.

I opened this items to version it -- added a version comment and added a new author, then clicked "Deposit." The page seemed to reload without my changes saved. I reviewed the page and made the same changes as above. I noted that the email field was empty -- I don't know if it was initially or not. I added an email with the other info and tried again to deposit and I got the same sort of page reload and my changes were again not saved -- no version comment, no new author, and this time no email address. When I check on the status, it is showing as deposited instead of being in a draft state.

Also, every time I try to version it I receive the email that there is new activity on this item.

![Screen Recording 2021-04-21 at 5.26.53 PM.gif](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c5a5d5f2-4dbc-4343-91ee-6428fdfdfdd8)

**Comment by jcoyne** [comment] 2021-05-05 16:43
What should the behavior be when this happens?  Do we want the versions in h2 to be the count of changes the user has made or do we want it to be synched up with what is in Argo?

**Comment by amyehodge** [comment] 2021-05-05 17:05
Based on previous discussions, I believe we decided that the versions don't need to sync up with what Argo says, but we do want to see the embargo release in the H2 history, though I'm not sure it needs to be a new version. The new version of the object created after the embargo release should be logged in both places.

**Comment by jermnelson** [comment] 2021-05-11 20:36
@amyehodge and @jcoyne, after some investigation part of the problem is that because the embargo date is no longer in the future, a validation error is occurring for that field when clicking the **Deposit** button. I believe that the reason this is not showing up as an error in the UI is because a second error is occurring related to: 
```
ActionView::Template::Error (undefined method `work_versions_path' for #<Works::ButtonsComponent:0x00007fd96caac308> 
Did you mean?  work_version_path                                                                                     
               work_version_url):                                                                                    
     7: <% end %>                                                                                                    
     8: <main class="mb-3 mb-md-5" id="content">                                                                     
     9:   <div class="container px-4 px-md-3">                                                                       
    10:     <%= render Works::FormComponent.new(work_form: @form) %>                                                 
    11:   </div>                                                                                                     
    12: </main>
```

This returns a 500 error from the server that prevents the client from rendering the error. 

I'm tracking down the cause of the second error but in the meantime, how should we handle the expired embargo date in H2 when editing a new Work version?

**Comment by amyehodge** [comment] 2021-05-12 14:54
@jcoyne and @jermnelson So, the behavior would be this?
User creates new item with an embargo date and (maybe does some editing of the draft one or more times and) deposits it with an embargo date, set for the future (of course).

Then one of two scenarios happens:
1. Embargo is released. After this date, user goes in to version the item. Once the new version is opened, the embargo date is no longer populated. Future saving and depositing to create a new version then does not require validation of this field, which would have been an issue b/c the date is in the past.
2. User goes in to version the item before the embargo date has passed. In this case, the form would retain the embargo date and continue to validate that field for deposit of the new version.

This sounds reasonable to me.

**Comment by jermnelson** [comment] 2021-05-12 21:51
@jcoyne, you're [comment](https://github.com/sul-dlss/happy-heron/pull/1424#pullrequestreview-658327485) regarding not closing this issue is confirmed with my testing on stage for this object. A `Cocina::RoundtripValidationError` from dor-services-app is causing this HB [alert](https://app.honeybadger.io/projects/50568/faults/79355918) with https://sul-h2-stage.stanford.edu/works/13246 still showing **Deposit In progress**. 

I stopped the retries queue in the API so we shouldn't generate any more HB alerts and I'll continue to investigate.

**Comment by amyehodge** [comment] 2021-06-22 14:25
@jcoyne @jermnelson  I just tested this and it still seems to be behaving as I described above. Here's what I did:
- Yesterday I created https://sul-h2-stage.stanford.edu/works/18052 and set it for embargo release today.
- Today I checked that embargo was lifted. It was -- I can download files from PURL and the embargo release is noted in the history.
- I then attempted to version the item. I opened it, added a version comment, added two files, and added in new keywords (removing the one old one). 
- When I clicked deposit it behaved as described above: seemed to reload the page with the version comments gone and no error messages. My changes had also been wiped out. 

This also triggered the HB alert pasted in below. 


Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/78962177

NoMethodError: undefined method `work_versions_path' for #<Works::ButtonsComponent:0x...> Did you mean? work_version_path work_version_url

Summary

works#update

URL: https://sul-h2-stage.stanford.edu/works/18052

Hostname: sul-h2-stage.stanford.edu

Context

user_scope: user
user_id: 12
user_email: amyhodge@stanford.edu
Trace

app/components/works/buttons_component.html.erb:12:in `call`
app/components/works/form_component.html.erb:35:in `block in call`
app/components/works/form_component.html.erb:2:in `call`

**Comment by justinlittman** [comment] 2021-06-22 20:20
@amyehodge This should probably be re-tested after https://github.com/sul-dlss/happy-heron/pull/1656 is deployed. I'm not suggesting it will fix the problem, but I suspect it will affect it.

**Comment by jcoyne** [comment] 2021-06-22 22:13
I agree with @justinlittman here. We've had significant change and I'm not sure that the bug you hit has anything to do with the embargo.

**Comment by amyehodge** [comment] 2021-06-23 13:06
@justinlittman and @jcoyne Sounds good. Let me know when #1656 has been deployed and I'll test this again.

**Comment by jcoyne** [comment] 2021-06-23 14:47
I think what may actually be going on here has to do with the remote validations and redrawing the page.  After an embargo is lifted and you try to save, the embargo will trigger an error because it is in the past, when this happens, the form is redrawn (422 response).  But I don't think it's then possible to make the form valid, which causes the HB error when you correct the embargo date.

**Closed** 2021-06-28 14:59 UTC
Labels: PO, R1.0, bug

**Comment by amyehodge** [comment] 2021-06-29 18:38
I have just created https://sul-h2-stage.stanford.edu/works/18075 and set an embargo to release tomorrow, June 30. I'll check back in on it tomorrow and complete the testing.
