### ISSUE TITLE
All objects deposited via H2 should have content type="file"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1899] opened 2021-08-05 21:38 UTC
I think we discussed early on setting these based on the work type chosen, but other work is needed to make these render properly on the PURL pages. 

Currently, some objects are being set to other content types, e.g. cg999mq8546. The work type is "media" and Argo shows 
![Screen Shot 2021-08-05 at 5.37.55 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/25ffdeb7-93d1-4858-b8ae-227eb1f6e52b)

which is causing the purl to look like this:
![Screen Shot 2021-08-05 at 5.38.26 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/8baef4d0-48b3-4023-991a-368b7aab892b)

**Comment by jcoyne** [comment] 2021-08-06 02:48
Is this a duplicate of #608?

**Comment by andrewjbtw** [comment] 2021-08-06 04:21
In a way, but this test item was somehow deposited with content type media https://argo.stanford.edu/view/cg999mq8546 It was deposited June 24 and the events indicate it came via the API, so I'm assuming it was created by H2.

**Comment by andrewjbtw** [comment] 2021-08-06 04:32
I just created an item with work type of video in stage and it came out as moving image:
https://argo-stage.stanford.edu/view/druid:wr200wv1607
https://sul-h2-stage.stanford.edu/works/18388

**Comment by amyehodge** [comment] 2021-08-06 18:16
Sounds like this is a problem we need to try to get to, as it's making the content inaccessible on the PURL.

**Closed** 2021-08-10 18:49 UTC
Labels: PO, R1.3
