### ISSUE TITLE
Notify users of encoding errors before they submit items

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1898] opened 2021-08-05 20:57 UTC
Similar to the error found in for jx225zq1407  “Encoding::UndefinedConversionError: “\xE2" from ASCII-8BIT to UTF-8". 

This got stuck on the back end and left the user watching the "Depositing" icon spinning. We need to identify any problems like this that will interfere with deposit so the user can fix them before they cause the object to get stuck.

**Comment by andrewjbtw** [comment] 2021-08-06 00:56
Since this druid made it through Hydrus with this character encoding last fall, is this something that could be addressed in H2 or the SDR API? It seems like some of the system is able to process the characters already.

**Comment by jcoyne** [comment] 2021-08-06 18:33
This is not an encoding error in the submission. This is an error in serializing the error message to JSON so it can be persisted in the database in SDR-API.  The original error message was a "failed to roundtrip" error in DSA and that error has been cleared.

**Comment by amyehodge** [comment] 2021-08-06 18:56
So, it sounds like we can close this? I'm fine with that.

**Comment by jcoyne** [comment] 2021-08-06 20:21
I think so. In any case the problem is not in h2.

**Closed by jcoyne** 2021-08-06 20:22 UTC
Labels: bug, PO, R1.3
