### ISSUE TITLE
Add the ability to revert/discard an already saved work in the database to the previous state it had when last deposited

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#858] opened 2021-01-15 19:34 UTC
Users need to be able to revert a version draft of a work, which would set it back to the last deposited state, thereby removing any changes they made in the version.

Since some changes take effect immediately, and since the work is immediately saved in the database when the user clicks the save draft button, this may require some versioning of database rows and other changes.

Note: collection reversion now in #1055

**Comment by jcoyne** [comment] 2021-01-26 05:02
I believe this is a duplicate of #26

**Comment by amyehodge** [comment] 2021-01-26 16:20
These look like duplicates to me as well.

**Comment by peetucket** [comment] 2021-01-27 22:25
Also see #794 for collections

**Comment by jcoyne** [comment] 2021-02-09 17:31
@amyehodge Should the managers, depositors, and reviewers of a Collection be versioned as well?  That is should they not take effect until the collection is versioned?

**Comment by jcoyne** [comment] 2021-02-10 05:02
@amyehodge @astridu do we have mock-ups for the user interface component of this?

**Comment by amyehodge** [comment] 2021-02-10 16:22
@jcoyne I don't think anything is needed for items. For collections, @astridu is working on the mockups. I was planning to file a separate ticket for that, but let me know if it should go here.

**Closed** 2021-02-16 23:48 UTC
Labels: PO, beta requirement
