### ISSUE TITLE
Failure to properly import license settings prevents user from viewing the list of items in an imported collection.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1252] opened 2021-03-04 00:48 UTC
I got this honeybadger error earlier when trying to view details in a couple of imported collections:

```
Error detected in: happy-heron (stage)

Full report at https://app.honeybadger.io/projects/77112/faults/76940953

TypeError: Parameter 'work_version': Expected type WorkVersion, got type NilClass Caller: /opt/app/h2/happy-heron/shared/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.6294/lib/types/private/methods/call_validation.rb:78 Definition: /opt/app/h2/happy-heron/releases/20210303182230/app/components/works/detail_component.rb:8

Summary

works#index

URL: https://sul-h2-stage.stanford.edu/collections/557/works

Hostname: sul-h2-stage.stanford.edu

Context

user_scope: user
user_id: 12
Trace

app/components/works/link_to_show_component.rb:16:in `new`
app/components/works/link_to_show_component.rb:16:in `title`
app/components/works/link_to_show_component.rb:12:in `link`
```

I later determined that these two collections did not have a license selected and that when I chose one, saved it, and redeposited it (though I don't understand why redeposit was required it), I was then able to view the list of items in the collection.

**Comment by amyehodge** [comment] 2021-04-21 18:33
Related to #1280

**Comment by jcoyne** [comment] 2021-05-05 18:15
Duplicate of #1374

**Closed by jcoyne** 2021-05-05 18:15 UTC
Labels: Migration, PO, R1.0, bug
