### ISSUE TITLE
Ensure review workflow (mediated deposits) is compatible with versioning

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#516] opened 2020-11-19 18:02 UTC
Ensure that when an object is versioned, that on the next version it continues to go through the review workflow.

**Comment by amyehodge** [comment] 2020-11-24 01:42
See mockup in wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/428088403 and 
Design Doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.3nd0v0kp7034

At mid-sprint check-in we discussed that this would autopopulate as information is filled in. This would include a placeholder link for the PURL (something like "_Link to PURL will be included here_.") Once the item is deposited and the PURL is available, the item view page will update so that the citation includes the citation as it will look on the PURL page. This should ideally also be updated in the citation box in the deposit form so that the user doesn't get confused about that text. 

If a depositor switches to the toggle to be able to edit the citation, whatever is in the box should stay there, but the content will no longer autoupdate. If they leave the placeholder text, then the link should be inserted, but if they delete it, then it won't be. (I'm sure we discussed that last bit, but I think it was implied and makes the most sense to me.)

Note that this means the PURL info in the citation will not be preserved.

**Comment by amyehodge** [comment] 2020-11-24 01:47
What is currently happening:

1. Depositor chooses to edit an item that has already been deposited into a collection with the review workflow turned on.
2. Edit page loads up. **Box at the top to add a description of your changes is missing.**
3. Depositor makes changes (in this case, swapped the descriptions on two files)
4. Clicked deposit button. Validations ran but content was not deposited.
5. Scrolled back up page to see that everything looks okay.
6. Clicked instead on save draft and that worked fine.

I suspect the problem is that the version comments are required but that box is not showing up.
I have not yet verified what is happening in Argo.

**Comment by mjgiarlo** [comment] 2020-11-24 16:15
@amyehodge thanks for testing and writing this up!

**Comment by mjgiarlo** [comment] 2020-11-24 16:23
I suspect what is happening behind the scenes triggered a HB alert: `StateMachines::InvalidTransition: Cannot transition state via :submit_for_review from :version_draft (Reason(s): State cannot transition via "submit for review")`

We likely need to add a transition to the submit_for_review event that allows works to move from version_draft to pending_approval: https://github.com/sul-dlss/happy-heron/blob/main/app/models/work.rb#L46

**Closed** 2020-11-30 19:18 UTC
Labels: PO

**Comment by mjgiarlo** [comment] 2020-11-30 19:45
@amyehodge This is now available for testing on QA and Stage.

**Comment by amyehodge** [comment] 2020-12-03 17:40
I finally checked this on stage and it seems to be working fine now. Thanks.
