### ISSUE TITLE
object not in 'first_draft' state after fetch_globus_job completed

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3071] opened 2023-05-17 21:10 UTC
~~During the week of May 15, we saw two unexplained issues:~~ (moved first issue to it's own ticket #3134)

HB error: https://app.honeybadger.io/projects/77112/faults/96031287

```
    "backtrace": [
      {
        "number": "224",
        "file": "[GEM_ROOT]/gems/state_machines-0.5.0/lib/state_machines/event.rb",
        "method": "block in add_actions",
        "source": {
          "222": "      # Fires the event, raising an exception if it fails\n",
          "223": "      machine.define_helper(:instance, \"#{qualified_name}!\") do |machine, object, *args|\n",
          "224": "        object.send(qualified_name, *args) || raise(StateMachines::InvalidTransition.new(object, machine, name))\n",
          "225": "      end\n",
          "226": "    end\n"
        }
      },
 snip...
    "component": "FetchGlobusJob",
    "action": "perform",
snip ...
    "message": "StateMachines::InvalidTransition: Cannot transition state via :fetch_globus_complete from :first_draft (Reason(s): State cannot transition via \"fetch globus complete\")",
snip ...
    "created_at": "2023-06-08T19:21:02.267999Z",
    "causes": [
      {
        "class": "Sidekiq::JobRetry::Skip",
        "message": "Sidekiq::JobRetry::Skip",
        "backtrace": [
...
        ]
      }
    ]

```

Work ID 6598 (first draft) was a single ZIP file added via globus.  It triggered this HB alert from `app/jobs/fetch_globus_job.rb`: https://app.honeybadger.io/projects/77112/faults/96031287  

The HB alert suggests the job completed, but the object was not in the correct state (`fetch_globus_first_draft`) to allow the transition back to `first_draft` to occur.    

The code suggests that the work_version should go into the `fetch_globus_first_draft` state before the job is run, and then the job is completed, it should go back to the `first_draft` state via the `fetch_globus_complete` transition in `app/jobs/fetch_globus_job.rb`.  

Running the job again by initiating the event `fetch_globus` allowed the job to run successfully with no HB alerts, so it's not clear why one of the transitions didn't work the first time.  May be related to #3005

**Comment by ndushay** [comment] 2023-06-27 19:03
one occurrence June 1;  two occurrences June 8

**Comment by ndushay** [comment] 2023-06-27 23:46
If this is related to issue #3005 (which is a valid question) then this might be happening when globus can't talk to h2 for whatever reason.  

@amyehodge @lwrubel  - is there a way we can get better errors sent to us from the globus side when they can't connect?

**Comment by amyehodge** [comment] 2023-06-28 14:32
@ndushay Another question for Karl?

**Comment by ndushay** [comment] 2023-06-28 18:02
per standup this morning, we are closing this because:
- we will have info about the calling state going forward due to PR #3132 (done to address #3005)
- we will have no more globus_setup_first_draft state and some other simplifications of the state machine from work Laura is doing on #3021

It is possible the causes of errors like this are one or more of
- network glitches in the middle of jobs, causing state changes to be dropped inadvertently
- retries of jobs that are effectively done, with or without the state changes
- other, which the above work should reduce the complexity of it

**Comment by lwrubel** [comment] 2023-07-06 14:35
Re-opening since this is still occurring with the fetch_globus_complete transition, after updates related to previous states  having been merged. See https://app.honeybadger.io/projects/77112/faults/94881665

(We no longer have globus_setup_complete errors since that event and its transitioning states no longer exist.)

**Comment by lwrubel** [comment] 2023-07-06 15:49
Transition errors do not consistently occur. They happen when there is no `params[:work][:fetch_globus_files]`, so the state does not get changed from `first_draft` to `fetch_globus_first_draft` via https://github.com/sul-dlss/happy-heron/blob/7aaf7b57bc95c685c94431aac1589870b296c97f/app/controllers/works_controller.rb#L194.

In the case where the invalid transition error occurs, the FetchGlobusJob fails but is then retried. In the meantime, the state DOES get updated to `fetch_globus_first_draft` and the retry and transition event successfully completes.

**Closed** 2023-07-13 19:38 UTC
Labels: 2023, other
