### ISSUE TITLE
Publication date validation should consider month and day, not just year

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#523] opened 2020-11-19 21:54 UTC
Publication dates that occur later in the current year are validating when they shouldn't

![Screen Shot 2020-11-19 at 1.54.17 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/c8031cab-0592-4efd-a2d7-2b5365f5945b)

**Comment by jcoyne** [comment] 2020-11-21 00:53
@amyehodge is this the same as #373?

**Comment by jmartin-sul** [comment] 2020-12-04 21:17
ran into this while working on #560 and was filing an issue, then realized it was a dupe of this one.

a bit more detail for whoever picks this up:  i noticed that the validation seemed to be happening on the server-side, and an error was sent back when i tried to deposit, it just didn't get presented to me in the UI (per the screenshot in the description).

e.g.:
<img width="1319" alt="Screen Shot 2020-12-04 at 1 12 28 PM" src="https://user-images.githubusercontent.com/7741604/101215630-0597d280-3633-11eb-842f-a28d1ec799ae.png">

**Closed** 2021-01-27 22:54 UTC
Labels: PO
