### ISSUE TITLE
Add embargo date to edit page

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#44] opened 2020-08-18 17:08 UTC
<img width="916" alt="Screen Shot 2020-10-09 at 8 05 11 AM" src="https://user-images.githubusercontent.com/92044/95586340-2c0c0980-0a06-11eb-8569-0e8dabdf51bb.png">

This should be stored in the embargo_date field.

See #118 for access after embargo.

**Comment by mjgiarlo** [comment] 2020-10-26 20:53
Closing as duplicate of #237

**Closed by mjgiarlo** 2020-10-26 20:53 UTC
