### ISSUE TITLE
Embargoed items that are supposed to be released to Stanford-only rights are instead being released to the world

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#2069] opened 2021-10-08 00:04 UTC
**Description of the problem**

H2 allows depositors to embargo their items for up to 3 years. During the embargo period, the files are not supposed to be available and the object should have the rights of "citation-only". These rights are not being set correctly and the result is that data is being made available before it should be released.

This ticket is for embargoed objects that are supposed to be released to Stanford visibility. I'll file a separate ticket for embargoed objects that should be released to world visibility.

**Details**

I created a test item and embargoed it until October 31. When released, it should be available only to the Stanford community. Instead, on the Purl the files have been made available to the Stanford community immediately:
https://sul-purl-stage.stanford.edu/cz498dt9764
https://argo-stage.stanford.edu/view/druid:cz498dt9764

In the embargo settings, the release is set to make the files available to the world on the release date:
```json
"embargo": {
      "access": "world",
      "download": "world",
      "releaseDate": "2021-10-31T00:00:00.000+00:00"
    },
```
It looks like what's happening is that the object level rights are correct: citation-only. But the files are being given file-level rights of "Stanford" that are overriding the object level rights. The files should not be downloadable by anyone during the embargo period.

These are the settings I chose in H2:
https://sul-h2-stage.stanford.edu/works/18549
<img width="1230" alt="Screen Shot 2021-10-07 at 4 41 36 PM" src="https://user-images.githubusercontent.com/8975583/136476507-ede0e54d-12db-4d6c-9b5b-3d618bde612e.png">

**Comment by peetucket** [comment] 2021-10-19 23:22
I made a PR that changes what is in cocina at the object level rights which I believe should fix this issue here: #2080 but I'm trying to understand the interplay between file level access rights and object level access rights.  Do you know if file level access rights are in cocina only and not reflected in the rightsMetadata?  I don't see anything having to do with files in the embargo release code: https://github.com/sul-dlss/dor-services/blob/main/lib/dor/services/embargo_service.rb#L16-L37

The other PRs I worked on will make file level access rights in cocina dark when something is embargoed, but I don't think anything will "fix" these file level access rights to reflect reality after the embargo is released.  I think it will all still work since the rightsMetadata datastream will be correct, but it won't be internally consistent to my understanding.

**Comment by andrewjbtw** [comment] 2021-10-20 00:02
The rightsMetadata has to have file-level rights listed explicitly in the rightsMetadata, otherwise files get the object-level rights according to the Fedora-Cocina mappings. In this case, the embargo release should replace the citation-only rightsMetadata with a Stanford rightsMetadata and the mappings should apply those Stanford rights to all the files. At least, it shouldn't look different than if someone chose Stanford rights from the start.

**Comment by mjgiarlo** [comment] 2021-11-05 17:33
Current state (via @andrewjbtw) :

* Items with world visibility look good
* However https://argo.stanford.edu/view/druid:gf072tq5537 (e.g.) should be set for Stanford release to Stanford (set to world instead)
* The issue where files were unintentionally available during the embargo period has been fixed in both cases

**Comment by mjgiarlo** [comment] 2021-11-05 20:45
@andrewjbtw and @amyehodge tested this in stage and confirmed the fix is good. Thanks, @peetucket! Merging the PR.

**Closed** 2021-11-05 20:46 UTC
Labels: bug, PO
